version: '3.8'

services:
  backend:
    build: 
      context: ./idatt2105-project-backend
      args:
        - password=${KEYSTORE_PASSWORD}
    ports:
      - "8443:8443"
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    depends_on:
      db:
        condition: service_healthy
    container_name: backend

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prosjekt
    container_name: db
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 5s
          retries: 10
  frontend:
    build: ./idatt2105-project-frontend
    ports:
      - "5173:5173"
    container_name: frontend
    depends_on:
      - backend