version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prosjekt
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prosjekt
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: