name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Docker Compose
        run: 
          |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Format code
        run: mvn spotless:apply

      - name: Check code
        run: mvn clean process-sources

      - name: Stop database container
        run: docker-compose down