name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose@v2

      - name: Start database container
        run: docker-compose up -d mysql

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Format code
        run: mvn spotless:apply

      - name: Check code
        run: mvn clean process-sources

      - name: Stop database container
        run: docker-compose down