name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: 
          |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Format code
        run: mvn spotless:apply

      - name: Check code
        run: mvn clean process-sources

      - name: Set up Docker
        uses: docker/setup-docker@v3

      - name: Build the Docker image
        run: |
          docker build . -t my-backend-image

      - name: Run the database container
        run: |
          docker-compose up -d
          docker-compose ps
          docker-compose exec mysql bash -c 'mysql -v'

      - name: Run the application
        run: docker run -p 8080:8080 -e "SPRING_DATASOURCE_URL=jdbc:mysql://mysql_prosjekt:3306/prosjekt" my-backend-image